#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

enum TokenType {
	_COMMENT_LITERAL_,
	_INTEGER_LITERAL_,
	_DOUBLE_LITERAL_,
	_BOOLEAN_LITERAL_,
	_STRING_LITERAL_,
	_IDENTIFIER_OR_KEYWORD_LITERAL_,
	_ARITHMETIC_OPERATOR_LITERAL_,
	_RELATIONAL_OPERATOR_LITERAL_,
	_LOGICAL_OPERATOR_LITERAL_,
	_OPEN_BRACKET_LITERAL_,
	_CLOSE_BRACKET_LITERAL_,
	_OPEN_PARENTHESIS_LITERAL_,
	_CLOSE_PARENTHESIS_LITERAL_,
	_OTHER_TOKEN_LITERAL_
};


#endif
